Ui specialist music detail screen
reediculous456/MusicLink pull request #20
Opened 2020-07-15 00:39 UTC by romigben

### Pull Request
Major changes that improves the apps layout and navigation
---------------------------------------------

#### Comments

2020-07-15 01:10 UTC, reediculous456 requested changes
Please remove the commented out code before we merge

2020-07-15 01:10 UTC, reediculous456 commented on app/src/main/res/layout/main_activity.xml
> +    <!--        android:layout_height="430dp">-->
Please remove the commented-out code

2020-07-15 01:10 UTC, reediculous456 commented on app/src/main/res/layout/main_activity.xml
> +    <!--    </androidx.recyclerview.widget.RecyclerView>-->
Please remove the commented-out code

2020-07-17 20:13 UTC, reediculous456 approved these changes

2020-07-18 19:40 UTC, devagrawal09 approved these changes

2020-07-19 03:12 UTC, katievo-1 approved these changes

2020-07-19 03:14 UTC, merged