redid admob banners
reediculous456/MusicLink pull request #29
Opened 2020-07-31 19:29 UTC by katievo-1

### Pull Request

---------------------------------------------

#### Comments
Please test

2020-07-31 19:51 UTC, reediculous456 requested changes
Can you make the ad banner fill the width of the screen and/or have the bottom touch the top of the nav
<img width="318" alt="Screen Shot 2020-07-31 at 3 50 26 PM" src="https://user-images.githubusercontent.com/24629474/89071868-8ffabd80-d345-11ea-991b-90cfea3556ed.png">

2020-07-31 20:22 UTC, reediculous456 submitted a review, later dismissed

2020-07-31 21:23 UTC, romigben approved these changes

2020-08-01 01:09 UTC, reediculous456 approved these changes

2020-08-01 01:10 UTC, merged